x-buzzy-defaults: &buzzy-defaults
  extra_hosts:
    - "host.docker.internal:host-gateway"
    - "buzzy.io:host-gateway"
    - "api.buzzy.io:host-gateway"
    - "login.buzzy.io:host-gateway"
    - "ws.buzzy.io:host-gateway"
  restart: on-failure

services:
  buzzy_sso:
    <<: *buzzy-defaults
    build: buzzy-sso/.
    image: buzzy_sso
    container_name: buzzy_sso_app
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      SPRING_DATASOURCE_URL: jdbc:postgresql://buzzy_sso_db:5432/buzzy_sso_db?stringtype=unspecified&serverTimezone=UTC
      ISSUER_URL: http://login.buzzy.io
      KAFKA_BOOTSTRAP_SERVER: buzzy_kafka:9092
      BUZZY_SUCCESSFUL_REGISTRATION_TOPIC_NAME: buzzy-successful-registration
    depends_on:
      buzzy_sso_db:
        condition: service_started
      buzzy_kafka:
          condition: service_started
  buzzy_sso_db:
    <<: *buzzy-defaults
    image: postgres:15-alpine
    container_name: buzzy_sso_app_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: buzzy_sso_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - buzzy_sso_db_data:/var/lib/postgresql/data

  buzzy_api:
    <<: *buzzy-defaults
    build: buzzy-api/.
    image: buzzy_api
    container_name: buzzy_api_app
    ports:
      - "8088:8088"
    environment:
      SERVER_PORT: 8088
      SPRING_DATASOURCE_URL: jdbc:postgresql://buzzy_api_db:5432/buzzy_api_db?stringtype=unspecified&serverTimezone=UTC
      INTROSPECTION_URL: http://login.buzzy.io/oauth2/introspect
      KAFKA_BOOTSTRAP_SERVER: buzzy_kafka:9092
      BUZZY_SUCCESSFUL_REGISTRATION_TOPIC_NAME: buzzy-successful-registration
      BUZZY_SUCCESSFUL_REGISTRATION_GROUP: buzzy-successful-registration-group
    depends_on:
      buzzy_api_db:
        condition: service_started
      buzzy_kafka:
        condition: service_started
      buzzy_sso:
        condition: service_started
      buzzy_websockets_server:
        condition: service_started
  buzzy_api_db:
    <<: *buzzy-defaults
    image: postgres:15-alpine
    container_name: buzzy_api_db_app
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: buzzy_api_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - buzzy_api_db_data:/var/lib/postgresql/data

  buzzy_webapp:
    <<: *buzzy-defaults
    build: buzzy-webapp/.
    image: buzzy_webapp
    container_name: buzzy_webapp_app
    ports:
      - "3000:8080"
    depends_on:
      buzzy_sso:
        condition: service_started
      buzzy_api:
          condition: service_started

  buzzy_websockets_server:
    <<: *buzzy-defaults
    build: buzzy-websockets-server/.
    image: buzzy_websockets_server
    container_name: buzzy_websockets_server_app
    ports:
      - "8085:8085"
    depends_on:
      buzzy_redis:
        condition: service_started

  buzzy_redis:
    <<: *buzzy-defaults
    image: redis
    container_name: buzzy_redis_server
    ports:
      - "6379:6379"
    volumes:
      - buzzy_redis_data:/data

  buzzy_kafka_ui:
    <<: *buzzy-defaults
    image: provectuslabs/kafka-ui:latest
    container_name: buzzy_kafka_ui_app
    ports:
      - "9090:8080"
    environment:
#      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: buzzy_kafka:9092
    depends_on:
      buzzy_kafka:
        condition: service_started

  buzzy_kafka:
    <<: *buzzy-defaults
    image: bitnami/kafka
    container_name: buzzy_kafka_server
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@buzzy_kafka:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://buzzy_kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - buzzy_kafka_data:/data

  buzzy_nginx:
    <<: *buzzy-defaults
    image: nginx
    container_name: buzzy_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./buzzy.io.conf:/etc/nginx/conf.d/buzzy.io.conf:ro


volumes:
  buzzy_sso_db_data:
  buzzy_api_db_data:
  buzzy_redis_data:
  buzzy_kafka_data: